const DAY = 24 * 60 * 60 * 1000;

function isoDaysAgo(days) {
  return new Date(Date.now() - days * DAY).toISOString();
}

export const entityLabels = {
  tasks: 'Tasks',
  recipes: 'Recipes',
  movies: 'Movies',
};

export const initialDashboardData = {
  tasks: [
    {
      id: 'task-1',
      title: 'Build overview section',
      description: 'Create a clear dashboard summary with task, recipe and movie cards.',
      category: 'design',
      status: 'active',
      priority: 'high',
      dueDate: '2026-04-05',
      notes: 'Use a warm but professional visual direction.',
      createdAt: isoDaysAgo(6),
      updatedAt: isoDaysAgo(2),
    },
    {
      id: 'task-2',
      title: 'Review recipe filters',
      description: 'Make sure cuisine and difficulty filters behave consistently.',
      category: 'content',
      status: 'completed',
      priority: 'medium',
      dueDate: '2026-03-29',
      notes: 'Double-check the responsive layout on mobile.',
      createdAt: isoDaysAgo(10),
      updatedAt: isoDaysAgo(1),
    },
    {
      id: 'task-3',
      title: 'Animate movie gallery cards',
      description: 'Add subtle motion and a lazy details panel for the film collection.',
      category: 'ui',
      status: 'active',
      priority: 'medium',
      dueDate: '2026-04-09',
      notes: 'Keep animation lightweight.',
      createdAt: isoDaysAgo(4),
      updatedAt: isoDaysAgo(4),
    },
  ],
  recipes: [
    {
      id: 'recipe-1',
      title: 'Citrus pasta salad',
      description: 'A fast spring salad with lemon dressing and fresh herbs.',
      cuisine: 'Mediterranean',
      difficulty: 'easy',
      status: 'published',
      prepTime: 15,
      cookTime: 10,
      servings: 2,
      ingredients: ['Pasta', 'Lemon', 'Parsley', 'Olive oil'],
      notes: 'Great for lunch prep.',
      createdAt: isoDaysAgo(8),
      updatedAt: isoDaysAgo(3),
    },
    {
      id: 'recipe-2',
      title: 'Spiced pumpkin soup',
      description: 'Comforting soup with roasted pumpkin and ginger.',
      cuisine: 'European',
      difficulty: 'medium',
      status: 'draft',
      prepTime: 20,
      cookTime: 35,
      servings: 4,
      ingredients: ['Pumpkin', 'Onion', 'Ginger', 'Cream'],
      notes: 'Top with pumpkin seeds.',
      createdAt: isoDaysAgo(12),
      updatedAt: isoDaysAgo(5),
    },
    {
      id: 'recipe-3',
      title: 'Berry overnight oats',
      description: 'No-cook breakfast with yogurt, oats and berries.',
      cuisine: 'Breakfast',
      difficulty: 'easy',
      status: 'published',
      prepTime: 10,
      cookTime: 0,
      servings: 1,
      ingredients: ['Oats', 'Yogurt', 'Berries', 'Chia seeds'],
      notes: 'Keep in the fridge overnight.',
      createdAt: isoDaysAgo(2),
      updatedAt: isoDaysAgo(1),
    },
  ],
  movies: [
    {
      id: 'movie-1',
      title: 'Arrival',
      description: 'A thoughtful sci-fi story about communication and time.',
      genre: 'Sci-Fi',
      status: 'watched',
      rating: 4.8,
      year: 2016,
      director: 'Denis Villeneuve',
      posterUrl: '',
      notes: 'Elegant, slow-burn visuals.',
      createdAt: isoDaysAgo(30),
      updatedAt: isoDaysAgo(7),
    },
    {
      id: 'movie-2',
      title: 'La La Land',
      description: 'A musical romance with a bright cinematic palette.',
      genre: 'Romance',
      status: 'watchlist',
      rating: 4.5,
      year: 2016,
      director: 'Damien Chazelle',
      posterUrl: '',
      notes: 'Perfect reference for colorful UI motion.',
      createdAt: isoDaysAgo(20),
      updatedAt: isoDaysAgo(10),
    },
    {
      id: 'movie-3',
      title: 'The Grand Budapest Hotel',
      description: 'Stylized comedy with sharp visual composition.',
      genre: 'Comedy',
      status: 'watched',
      rating: 4.7,
      year: 2014,
      director: 'Wes Anderson',
      posterUrl: '',
      notes: 'Use as inspiration for card layout.',
      createdAt: isoDaysAgo(18),
      updatedAt: isoDaysAgo(4),
    },
  ],
};

